// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBe_0Hm2yhj1kjBr1swX8l51hQgI4r6PQ',
    appId: '1:432655298375:android:c3d5f6164c7938eb68e662',
    messagingSenderId: '432655298375',
    projectId: 'gogobooking-5ade1',
    databaseURL: 'https://gogobooking-5ade1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gogobooking-5ade1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAqRyEcXUp5PZMZ__AMubVmCzqDODbkkE',
    appId: '1:432655298375:ios:a3684d01ff176ccd68e662',
    messagingSenderId: '432655298375',
    projectId: 'gogobooking-5ade1',
    databaseURL: 'https://gogobooking-5ade1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gogobooking-5ade1.appspot.com',
    iosBundleId: 'com.example.driverApp',
  );
}
